Base:
  assetsPath: "data/assets_test2.csv"

Steps:
  BaseScreeningStep:
    enable: False
    outputPath: "data/base_screening.csv"

  ImbalanceScreeningStep:
    enable: True
    4hOhlcHistory: 180 # 30 days
    dailyOhlcHistory: 90 # 1 quarter
    weeklyOhlcHistory: 520 # 10 years
    monthlyOhlcHistory: 120 # 10 years
    outputBuyerImbalancePath: "data/imbalance_buyer_screening.csv"
    outputSellerImbalancePath: "data/imbalance_seller_screening.csv"

Services:
  DataDownloader:
    rateExceedDelaySeconds: 60
