base:
  assetsPath: "data/assets.csv"
  cryptoHistoryDbPath: "../../database/crypto_history.sqlite"
  cryptoScreenerDbPath: "../../database/crypto_screener.sqlite"

steps:
  dataDownloadStep:
    enable: True
    fourHoursOhlcHistory: 180 # 30 days
    dailyOhlcHistory: 201 # about 1/2 year
    weeklyOhlcHistory: 520 # 10 years
    monthlyOhlcHistory: 120 # 10 years

  baseScreeningStep:
    enable: True

  imbalanceScreeningStep:
    enable: True

  loadProcessedImbalancesStep:
    enable: True
    buyerImbalancesPath: "data/buyer_imbalances_processed.csv"
    sellerImbalancesPath: "data/seller_imbalances_processed.csv"

services:
  dataDownloader:
    rateExceedDelaySeconds: 60
    binanceNotSupportedPairs:
      - HNTUSDT
